import Link from 'next/link';
import { SiteHeader } from './site-header';
import { SiteFooter } from './site-footer';
import { Reveal } from './reveal';
import { VisualSlot } from './visual-slot';
import { AlbumGallery } from './album-gallery';
import { collections, pageVisuals, services, studio, tourism, type Collection } from '@/lib/collections';

export function PageShell({ children }: { children: React.ReactNode }) { return <><a href="#contenuto" className="fixed left-6 top-4 z-50 -translate-y-32 bg-sand px-5 py-3 text-ink focus:translate-y-0">Vai al contenuto</a><SiteHeader /><main id="contenuto" tabIndex={-1}>{children}</main><SiteFooter /></>; }
export function PageIntro({ title, eyebrow, description, visual }: { title: string; eyebrow: string; description?: string; visual?: string }) { return <section className="px-6 pb-16 pt-44 md:px-10 md:pb-24 md:pt-56 xl:px-16"><p className="mb-7 text-xs uppercase tracking-[.2em] text-sand">{eyebrow}</p><h1 className="max-w-6xl font-display text-[clamp(3.3rem,10vw,10rem)] leading-[1.02] tracking-[-.04em] [overflow-wrap:anywhere]">{title}<span className="text-sand">.</span></h1>{description && <p className="mt-8 max-w-xl text-base leading-relaxed text-white/65 md:ml-auto md:text-lg">{description}</p>}{visual && <div className="mt-14 md:mt-24"><VisualSlot visual={pageVisuals[visual]} label={title} className="aspect-[4/3] md:aspect-[21/9]" priority /></div>}</section>; }
export function EventCTA({ type }: { type?: string }) { return <div className="px-6 pb-24 pt-8 md:px-10 md:pb-36 xl:px-16"><Link href={`/contatti${type ? `?evento=${encodeURIComponent(type)}` : ''}`} className="inline-flex min-h-14 items-center gap-8 border-b border-sand pb-4 text-lg hover:text-sand">Raccontaci il tuo evento <span aria-hidden="true">↗</span></Link></div>; }
export function CategoryIndex({ group }: { group: 'party' | 'events' }) { const items=collections.filter(c=>c.group===group); return <PageShell><PageIntro title={group === 'party' ? 'Party' : 'Events'} eyebrow={`Events Studio / ${group}`} description={group === 'party' ? 'Feste private e diciottesimi. La tua occasione prende forma.' : 'Wedding, aziende, piazze e spettacoli. Quattro modi di vivere un evento.'} visual={group} /><section aria-label={`Esplora ${group}`} className="space-y-20 px-6 pb-24 md:space-y-36 md:px-10 xl:px-16">{items.map((item,index)=><Reveal key={item.slug}><Link href={`/${group}/${item.slug}`} className={`group block ${index % 2 ? 'md:ml-[20%]' : 'md:mr-[12%]'}`}><VisualSlot visual={item.cover} label={item.title} className={index%2 ? 'aspect-[4/3] md:aspect-[16/10]' : 'aspect-[4/3] md:aspect-[16/9]'} /><div className="mt-6 grid gap-5 border-t border-white/15 pt-5 md:grid-cols-[1fr_1fr]"><div><span className="text-xs text-sand">0{index+1}</span><h2 className="mt-2 font-display text-[clamp(2.3rem,5vw,5rem)] leading-tight group-hover:text-sand">{item.title}</h2></div><div className="md:pt-7"><p className="max-w-sm text-base leading-relaxed text-white/65">{item.description}</p><span className="mt-5 inline-flex min-h-11 items-center gap-5 text-sm">Esplora la gallery <span aria-hidden="true">↗</span></span></div></div></Link></Reveal>)}</section><EventCTA /></PageShell>; }
export function CollectionPage({ item }: { item: Collection }) { const next=collections[(collections.indexOf(item)+1)%collections.length]; return <PageShell><PageIntro title={item.title} eyebrow={`Events Studio / ${item.group}`} description={item.description} /><div className="px-6 md:px-10 xl:px-16"><Link href={`/${item.group}`} className="inline-flex min-h-11 items-center gap-4 text-sm text-sand">← Tutti gli {item.group === 'party' ? 'album Party' : 'Events'}</Link><VisualSlot visual={item.cover} label={item.title} className={`mt-7 ${item.slug === 'wedding' ? 'aspect-[4/5] md:aspect-[16/10]' : 'aspect-[4/3] md:aspect-[21/9]'}`} priority /></div><AlbumGallery images={item.images} title={item.title} /><EventCTA type={item.title} /><div className="px-6 pb-24 md:px-10 xl:px-16"><p className="mb-4 text-xs uppercase tracking-widest text-white/60">Continua a esplorare</p><Link href={`/${next.group}/${next.slug}`} className="font-display text-4xl hover:text-sand md:text-6xl">{next.title} ↗</Link></div></PageShell>; }
export function ServicesPage() { return <PageShell><PageIntro title="Servizi" eyebrow="Events Studio / In scena" description="Musica, intrattenimento, allestimenti. Le diverse dimensioni di un evento." /><div className="px-6 md:px-10 xl:px-16">{services.map((service,index)=><section id={service.slug} key={service.slug} className="grid gap-8 border-t border-white/20 py-14 md:grid-cols-[.8fr_1.2fr] md:gap-16 md:py-24"><div className="self-start md:sticky md:top-12"><span className="text-sm text-sand">0{index+1} / 06</span><h2 className="mt-7 font-display text-[clamp(2.5rem,4.7vw,5.4rem)] leading-[1.08]">{service.title}</h2><p className="mt-7 max-w-sm text-base leading-relaxed text-white/65">{service.description}</p><Link href={`/contatti?servizio=${encodeURIComponent(service.title)}`} className="mt-7 inline-flex min-h-11 items-center gap-6 border-b border-sand text-sm hover:text-sand">Parliamone <span aria-hidden="true">↗</span></Link></div><Reveal><VisualSlot visual={service.visual} label={service.title} className="aspect-[4/5]" /></Reveal></section>)}</div></PageShell>; }
export function AboutPage() { return <PageShell><PageIntro title="Chi siamo" eyebrow="Events Studio / Lo studio" visual="chi-siamo" /><section className="grid gap-12 px-6 pb-28 md:grid-cols-2 md:px-10 xl:px-16"><h2 className="font-display text-5xl md:text-7xl">La nostra<br /><span className="text-sand">storia.</span></h2><div className="space-y-8 text-lg leading-relaxed text-white/65">{studio.story ? studio.story.split('\n\n').map((p,i)=><p key={i}>{p}</p>) : <p>La storia ufficiale di Events Studio sarà raccontata qui: le origini, il percorso e lo studio oggi. Testo in attesa del cliente.</p>}{studio.timeline.map(point=><div key={point.year} className="border-t border-white/20 pt-6"><h3 className="text-sand">{point.year}</h3><p>{point.text}</p></div>)}{studio.quote && <blockquote className="font-display text-3xl text-sand">{studio.quote}</blockquote>}{studio.facts.map(fact=><p key={fact.label}><strong className="font-display text-4xl text-sand">{fact.value}</strong><br />{fact.label}</p>)}</div></section><EventCTA /></PageShell>; }
export function TourismPage() { return <PageShell><PageIntro title="Tourism" eyebrow="Events Studio / Un altro sguardo" visual="tourism" /><section className="px-6 pb-20 md:px-10 xl:px-16"><div className="grid gap-10 md:grid-cols-2"><h2 className="font-display text-5xl md:text-7xl">Esperienze<br /><span className="text-sand">da scoprire.</span></h2><p className="max-w-lg text-lg leading-relaxed text-white/65">{tourism.introduction ?? 'La presentazione ufficiale di Tourism è in preparazione. Esperienze e destinazioni saranno pubblicate con i materiali forniti da Events Studio.'}</p></div>{[...tourism.experiences,...tourism.destinations].map((item,index)=><Reveal key={`${item.title}-${index}`}><article className="mt-20"><VisualSlot visual={item.visual} label={item.title} className="aspect-[4/3] md:aspect-[21/9]" /><h3 className="mt-7 font-display text-4xl">{item.title}</h3><p className="mt-4 max-w-xl text-white/65">{item.description}</p></article></Reveal>)}</section><AlbumGallery images={tourism.images} title="Tourism" /><EventCTA /></PageShell>; }
