// Fotografie originali fornite dal cliente. Derivati WebP senza ritocchi creativi.
export const photos = {
  "p0": {
    "id": "events-studio-00",
    "title": "L’attesa",
    "alt": "La sposa raggiunge gli ospiti nel cortile della location",
    "src": "/assets/images/events/wedding/events-studio-00-2400.webp",
    "srcSet": "/assets/images/events/wedding/events-studio-00-960.webp 960w, /assets/images/events/wedding/events-studio-00-2400.webp 2400w",
    "width": 2400,
    "height": 1600,
    "position": "50% 50%",
    "layout": "opening"
  },
  "p1": {
    "id": "events-studio-01",
    "title": "L’ingresso",
    "alt": "Gli sposi entrano nella sala tra luci e allestimenti bianchi",
    "src": "/assets/images/events/wedding/events-studio-01-2400.webp",
    "srcSet": "/assets/images/events/wedding/events-studio-01-960.webp 960w, /assets/images/events/wedding/events-studio-01-2400.webp 2400w",
    "width": 2400,
    "height": 1600,
    "position": "50% 50%",
    "layout": "opening"
  },
  "p3": {
    "id": "events-studio-03",
    "title": "Tutti in pista",
    "alt": "Gli invitati ballano insieme durante il ricevimento",
    "src": "/assets/images/events/wedding/events-studio-03-2400.webp",
    "srcSet": "/assets/images/events/wedding/events-studio-03-960.webp 960w, /assets/images/events/wedding/events-studio-03-2400.webp 2400w",
    "width": 2400,
    "height": 1600,
    "position": "50% 50%",
    "layout": "opening"
  },
  "p4": {
    "id": "events-studio-04",
    "title": "La festa",
    "alt": "Foto di gruppo in bianco e nero durante la festa",
    "src": "/assets/images/events/wedding/events-studio-04-2400.webp",
    "srcSet": "/assets/images/events/wedding/events-studio-04-960.webp 960w, /assets/images/events/wedding/events-studio-04-2400.webp 2400w",
    "width": 2400,
    "height": 1600,
    "position": "50% 50%",
    "layout": "opening"
  },
  "p5": {
    "id": "events-studio-05",
    "title": "L’abbraccio degli ospiti",
    "alt": "Gli sposi circondati dagli invitati nella sala del ricevimento",
    "src": "/assets/images/events/wedding/events-studio-05-2400.webp",
    "srcSet": "/assets/images/events/wedding/events-studio-05-960.webp 960w, /assets/images/events/wedding/events-studio-05-2400.webp 2400w",
    "width": 2400,
    "height": 1600,
    "position": "50% 50%",
    "layout": "opening"
  },
  "p7": {
    "id": "events-studio-07",
    "title": "Il primo ballo",
    "alt": "Gli sposi ballano sulla nebbia bassa accompagnati dalla violinista",
    "src": "/assets/images/events/wedding/events-studio-07-2400.webp",
    "srcSet": "/assets/images/events/wedding/events-studio-07-960.webp 960w, /assets/images/events/wedding/events-studio-07-2400.webp 2400w",
    "width": 2400,
    "height": 1600,
    "position": "50% 50%",
    "layout": "opening"
  },
  "p8": {
    "id": "events-studio-08",
    "title": "Luce ed emozione",
    "alt": "Fontane luminose ai lati della pista durante il ballo degli sposi",
    "src": "/assets/images/events/wedding/events-studio-08-2400.webp",
    "srcSet": "/assets/images/events/wedding/events-studio-08-960.webp 960w, /assets/images/events/wedding/events-studio-08-2400.webp 2400w",
    "width": 2400,
    "height": 1600,
    "position": "50% 50%",
    "layout": "opening"
  },
  "p9": {
    "id": "events-studio-09",
    "title": "Musica per il vostro giorno",
    "alt": "Una violinista suona accanto agli sposi durante il ricevimento",
    "src": "/assets/images/events/wedding/events-studio-09-2400.webp",
    "srcSet": "/assets/images/events/wedding/events-studio-09-960.webp 960w, /assets/images/events/wedding/events-studio-09-2400.webp 2400w",
    "width": 2400,
    "height": 1600,
    "position": "50% 50%",
    "layout": "opening"
  },
  "p11": {
    "id": "events-studio-11",
    "title": "La voce della festa",
    "alt": "Un animatore al microfono coinvolge gli ospiti durante il ricevimento",
    "src": "/assets/images/services/animatore/events-studio-11-2400.webp",
    "srcSet": "/assets/images/services/animatore/events-studio-11-960.webp 960w, /assets/images/services/animatore/events-studio-11-2400.webp 2400w",
    "width": 2400,
    "height": 1600,
    "position": "50% 50%",
    "layout": "opening"
  },
  "p12": {
    "id": "events-studio-12",
    "title": "Effetti in scena",
    "alt": "Performance all’aperto con getti scenici luminosi durante un matrimonio",
    "src": "/assets/images/services/show-production/events-studio-12-2400.webp",
    "srcSet": "/assets/images/services/show-production/events-studio-12-960.webp 960w, /assets/images/services/show-production/events-studio-12-2400.webp 2400w",
    "width": 2400,
    "height": 1600,
    "position": "50% 50%",
    "layout": "opening"
  },
  "p13": {
    "id": "events-studio-13",
    "title": "Il suono della luce",
    "alt": "Musicista con violino luminoso durante il ricevimento",
    "src": "/assets/images/services/musicisti-performer/events-studio-13-2400.webp",
    "srcSet": "/assets/images/services/musicisti-performer/events-studio-13-960.webp 960w, /assets/images/services/musicisti-performer/events-studio-13-2400.webp 2400w",
    "width": 2400,
    "height": 1600,
    "position": "50% 50%",
    "layout": "opening"
  },
  "p15": {
    "id": "events-studio-15",
    "title": "Note dal vivo",
    "alt": "Violinista e sassofonista durante una performance in bianco e nero",
    "src": "/assets/images/services/musicisti-performer/events-studio-15-2400.webp",
    "srcSet": "/assets/images/services/musicisti-performer/events-studio-15-960.webp 960w, /assets/images/services/musicisti-performer/events-studio-15-2400.webp 2400w",
    "width": 2400,
    "height": 1600,
    "position": "50% 50%",
    "layout": "opening"
  },
  "p16": {
    "id": "events-studio-16",
    "title": "Il ritmo",
    "alt": "DJ alla consolle durante un evento",
    "src": "/assets/images/services/dj/events-studio-16-2400.webp",
    "srcSet": "/assets/images/services/dj/events-studio-16-960.webp 960w, /assets/images/services/dj/events-studio-16-2400.webp 2400w",
    "width": 2400,
    "height": 1600,
    "position": "50% 50%",
    "layout": "opening"
  },
  "p17": {
    "id": "events-studio-17",
    "title": "Il taglio della torta",
    "alt": "Gli sposi davanti alla torta con il paesaggio sullo sfondo",
    "src": "/assets/images/events/wedding/events-studio-17-2400.webp",
    "srcSet": "/assets/images/events/wedding/events-studio-17-960.webp 960w, /assets/images/events/wedding/events-studio-17-2400.webp 1706w",
    "width": 1706,
    "height": 2560,
    "position": "50% 50%",
    "layout": "opening"
  },
  "p18": {
    "id": "events-studio-18",
    "title": "Insieme",
    "alt": "Gli sposi festeggiano insieme agli invitati nella sala",
    "src": "/assets/images/events/wedding/events-studio-18-2400.webp",
    "srcSet": "/assets/images/events/wedding/events-studio-18-960.webp 960w, /assets/images/events/wedding/events-studio-18-2400.webp 1706w",
    "width": 1706,
    "height": 2560,
    "position": "50% 50%",
    "layout": "opening"
  },
  "p19": {
    "id": "events-studio-19",
    "title": "Ali di luce",
    "alt": "Performer con grandi ali luminose sulla terrazza al tramonto",
    "src": "/assets/images/events/spettacoli/events-studio-19-2400.webp",
    "srcSet": "/assets/images/events/spettacoli/events-studio-19-960.webp 960w, /assets/images/events/spettacoli/events-studio-19-2400.webp 1706w",
    "width": 1706,
    "height": 2560,
    "position": "50% 50%",
    "layout": "opening"
  },
  "p20": {
    "id": "events-studio-20",
    "title": "Uno sguardo lontano",
    "alt": "Gli sposi a bordo piscina davanti al paesaggio montano",
    "src": "/assets/images/events/wedding/events-studio-20-2400.webp",
    "srcSet": "/assets/images/events/wedding/events-studio-20-960.webp 960w, /assets/images/events/wedding/events-studio-20-2400.webp 1706w",
    "width": 1706,
    "height": 2560,
    "position": "50% 50%",
    "layout": "opening"
  },
  "p21": {
    "id": "events-studio-21",
    "title": "Un momento da ricordare",
    "alt": "Gli sposi festeggiano con le braccia alzate in bianco e nero",
    "src": "/assets/images/events/wedding/events-studio-21-2400.webp",
    "srcSet": "/assets/images/events/wedding/events-studio-21-960.webp 960w, /assets/images/events/wedding/events-studio-21-2400.webp 1706w",
    "width": 1706,
    "height": 2560,
    "position": "50% 50%",
    "layout": "opening"
  },
  "p22": {
    "id": "events-studio-22",
    "title": "La meraviglia",
    "alt": "Performer con ali luminose aperte sulla terrazza",
    "src": "/assets/images/events/spettacoli/events-studio-22-2400.webp",
    "srcSet": "/assets/images/events/spettacoli/events-studio-22-960.webp 960w, /assets/images/events/spettacoli/events-studio-22-2400.webp 1706w",
    "width": 1706,
    "height": 2560,
    "position": "50% 50%",
    "layout": "opening"
  },
  "p23": {
    "id": "events-studio-23",
    "title": "La festa prende vita",
    "alt": "Animatore al microfono tra gli ospiti che agitano tovaglioli",
    "src": "/assets/images/party/feste-private/events-studio-23-2400.webp",
    "srcSet": "/assets/images/party/feste-private/events-studio-23-960.webp 960w, /assets/images/party/feste-private/events-studio-23-2400.webp 2400w",
    "width": 2400,
    "height": 1600,
    "position": "50% 50%",
    "layout": "opening"
  },
  "p24": {
    "id": "events-studio-24",
    "title": "Un sorriso condiviso",
    "alt": "Un’ospite e un animatore Events Studio al microfono in bianco e nero",
    "src": "/assets/images/party/feste-private/events-studio-24-2400.webp",
    "srcSet": "/assets/images/party/feste-private/events-studio-24-960.webp 960w, /assets/images/party/feste-private/events-studio-24-2400.webp 2400w",
    "width": 2400,
    "height": 1600,
    "position": "50% 50%",
    "layout": "opening"
  },
  "p25": {
    "id": "events-studio-25",
    "title": "Tutti protagonisti",
    "alt": "Gli ospiti partecipano a un momento di animazione con parrucche colorate",
    "src": "/assets/images/party/feste-private/events-studio-25-2400.webp",
    "srcSet": "/assets/images/party/feste-private/events-studio-25-960.webp 960w, /assets/images/party/feste-private/events-studio-25-2400.webp 2400w",
    "width": 2400,
    "height": 1600,
    "position": "50% 50%",
    "layout": "opening"
  },
  "p26": {
    "id": "events-studio-26",
    "title": "Scintille nella notte",
    "alt": "Fontane luminose e getti scenici colorati durante una festa serale",
    "src": "/assets/images/services/allestimenti-effetti/events-studio-26-2400.webp",
    "srcSet": "/assets/images/services/allestimenti-effetti/events-studio-26-960.webp 960w, /assets/images/services/allestimenti-effetti/events-studio-26-2400.webp 1179w",
    "width": 1179,
    "height": 1450,
    "position": "50% 50%",
    "layout": "opening"
  },
  "p27": {
    "id": "events-studio-27",
    "title": "Un’esplosione di colore",
    "alt": "Gli sposi si abbracciano davanti a un ventaglio di effetti colorati",
    "src": "/assets/images/events/wedding/events-studio-27-2400.webp",
    "srcSet": "/assets/images/events/wedding/events-studio-27-960.webp 960w, /assets/images/events/wedding/events-studio-27-2400.webp 1706w",
    "width": 1706,
    "height": 2560,
    "position": "50% 50%",
    "layout": "opening"
  },
  "p28": {
    "id": "events-studio-28",
    "title": "Il vostro momento",
    "alt": "Gli sposi davanti a una scenografia di fumo colorato",
    "src": "/assets/images/events/wedding/events-studio-28-2400.webp",
    "srcSet": "/assets/images/events/wedding/events-studio-28-960.webp 960w, /assets/images/events/wedding/events-studio-28-2400.webp 1706w",
    "width": 1706,
    "height": 2560,
    "position": "50% 50%",
    "layout": "opening"
  },
  "p29": {
    "id": "events-studio-29",
    "title": "Una nuova storia",
    "alt": "Gli sposi si tengono per mano nella sala del ricevimento",
    "src": "/assets/images/events/wedding/events-studio-29-2400.webp",
    "srcSet": "/assets/images/events/wedding/events-studio-29-960.webp 960w, /assets/images/events/wedding/events-studio-29-2400.webp 1706w",
    "width": 1706,
    "height": 2560,
    "position": "50% 50%",
    "layout": "opening"
  },
  "p31": {
    "id": "events-studio-31",
    "title": "Un ingresso speciale",
    "alt": "Una festeggiata sul tappeto bianco tra fontane luminose",
    "src": "/assets/images/party/feste-private/events-studio-31-2400.webp",
    "srcSet": "/assets/images/party/feste-private/events-studio-31-960.webp 960w, /assets/images/party/feste-private/events-studio-31-2400.webp 2400w",
    "width": 2400,
    "height": 1600,
    "position": "50% 50%",
    "layout": "opening"
  }
} as const;
