'use client';
import { useRef, useState } from 'react';
import { eventTypes } from '@/lib/contact';
export function ContactForm({ enabled, privacyUrl, initialEvent='', initialService='' }:{enabled:boolean;privacyUrl:string|null;initialEvent?:string;initialService?:string}) {
  const [status,setStatus]=useState(''); const [busy,setBusy]=useState(false); const [sent,setSent]=useState(false); const sending=useRef(false);
  const field='mt-3 min-h-12 w-full rounded-none border-b border-white/30 bg-transparent py-3 text-base text-white focus:border-sand focus:outline-none';
  return <section className="px-6 pb-28 md:px-10 xl:px-16" aria-labelledby="form-title"><div className="grid gap-12 border-t border-white/20 pt-10 lg:grid-cols-[.7fr_1.3fr]"><div><h2 id="form-title" className="font-display text-4xl leading-tight md:text-6xl">Raccontaci<br /><span className="text-sand">il tuo evento.</span></h2><p className="mt-6 max-w-sm text-base leading-relaxed text-white/60">Partiamo dalla tua idea. I campi contrassegnati con * sono obbligatori.</p>{!enabled && <p id="form-unavailable" className="mt-6 max-w-sm border-l border-sand pl-5 text-sm leading-relaxed text-white/70">Il modulo è in anteprima. L’invio sarà disponibile dopo l’attivazione del servizio e dell’informativa privacy.</p>}</div>
  <form aria-busy={busy} aria-describedby={!enabled?'form-unavailable':undefined} onSubmit={async event=>{event.preventDefault(); if(!enabled||sending.current)return; sending.current=true;setBusy(true);setStatus('');const form=event.currentTarget;const data=new FormData(form);try{const response=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...Object.fromEntries(data),privacy:data.get('privacy')==='on'})});const result=await response.json().catch(()=>({error:'Il servizio non è disponibile. Riprova più tardi.'}));if(!response.ok || result.ok !== true)throw new Error(result.error??'Invio non riuscito.');setSent(true);setStatus('Richiesta ricevuta. Grazie per averci raccontato il tuo evento.');form.reset();}catch(error){setStatus(error instanceof Error?error.message:'Invio non riuscito. Riprova.');}finally{sending.current=false;setBusy(false);}}} className="min-w-0">
    <div className="grid gap-x-8 gap-y-7 sm:grid-cols-2">{[{name:'nome',label:'Nome',auto:'given-name',type:'text'},{name:'cognome',label:'Cognome',auto:'family-name',type:'text'},{name:'telefono',label:'Telefono',auto:'tel',type:'tel'},{name:'email',label:'Email',auto:'email',type:'email'}].map(input=><label key={input.name} className="text-sm text-white/75">{input.label} *<input required maxLength={input.name==='telefono'?30:200} name={input.name} autoComplete={input.auto} type={input.type} className={field} /></label>)}
    <label className="text-sm text-white/75">Tipologia evento *<select name="tipologia" required defaultValue={eventTypes.includes(initialEvent)?initialEvent:''} className={field}><option value="" disabled>Seleziona</option>{eventTypes.map(type=><option key={type} value={type}>{type}</option>)}</select></label><label className="text-sm text-white/75">Data evento <span className="text-white/55">(facoltativa)</span><input name="data" type="date" className={field} /></label>
    <label className="text-sm text-white/75 sm:col-span-2">Città / Location *<input name="location" required maxLength={200} autoComplete="address-level2" className={field} /></label><label className="text-sm text-white/75 sm:col-span-2">Messaggio *<textarea required name="messaggio" rows={5} maxLength={4000} defaultValue={initialService?`Vorrei informazioni sul servizio ${initialService}.`:''} className={`${field} resize-y`} /></label></div>
    <div hidden aria-hidden="true"><label>Sito web<input name="website" tabIndex={-1} autoComplete="off" /></label></div>
    <label className="mt-8 flex min-h-11 items-start gap-4 text-sm leading-relaxed text-white/70"><input type="checkbox" name="privacy" required disabled={!privacyUrl} className="mt-1 size-5 shrink-0 accent-sand" /><span>Ho letto e accetto {privacyUrl?<a href={privacyUrl} target="_blank" rel="noopener noreferrer" className="underline underline-offset-4">l’informativa privacy</a>:'l’informativa privacy (da fornire)'}. *</span></label>
    <button type="submit" disabled={!enabled||busy||sent} className="mt-8 min-h-14 border border-sand px-8 py-4 text-sm uppercase tracking-widest text-sand transition-colors hover:bg-sand hover:text-ink disabled:border-white/25 disabled:text-white/55 disabled:hover:bg-transparent">{busy?'Invio in corso…':sent?'Richiesta inviata':enabled?'Invia richiesta':'Invio non ancora attivo'}</button><p role="status" aria-live="polite" className="mt-5 text-base leading-relaxed text-sand">{status}</p>
  </form></div></section>;
}

